title: RozeFound / Project D.D
email: rozefound@proton.me
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
domain: "rozefound.github.io"
url: "https://rozefound.github.io" # the base hostname & protocol for your site, e.g. http://example.com
sass:
  style: compressed
plugins:
  - jekyll-feed